#APPLICATION:
#  configuration:
#   # Advanced parameters defined by applications
#   advanced_configs:
#      default_group: group_name
#      groups:
#        - name: group_name
#          env_cfg: ENV_CONFIG
#          type: group_type (file/config)
#
#    # Mapping for jsonnet storage size, see WARP-17653
#    storage_resource:
#      normal_size_metric_from_template: DiskNormalSize
#      data_size_metric_from_template: DiskDataSize
#      log_size_metric_from_template: DiskLogSize
#      tmp_size_metric_from_template: DiskTmpSize
#
#    # Priority configs for applications
#    priority_metrics:
#      priority_config_name: default_value
#
#  optional_dependencies:
#    - example_dependency
#
#  security:
#    service_refer:
#      instance_type_1: instance_type_2

#CODIS:


DISCOVER:
  configuration:
    advanced_configs:
      default_group: spark-defaults.conf
      groups:
      - name: spark-defaults.conf
        env_cfg: DISCOVER_SPARK_DEFAULTS_CONFIGS
        type: file


#FILEBEAT:


#GOVERNOR:


GUARDIAN:
  configuration:
    storage_resource:
      guardian_server_volume_storage: DiskNormalSize
    storage_class_resource:
      guardian_server_volume_storage: DiskNormalStorageClass

HDFS:
  configuration:
    advanced_configs:
      default_group: hdfs-site.xml
      groups:
      - name: hdfs-site.xml
        env_cfg: HDFS_HDFS_SITE_CONFIGS
        type: file
      - name: core-site.xml
        env_cfg: HDFS_CORE_SITE_CONFIGS
        type: file
    storage_resource:
      hdfs_name_data_storage: DiskNormalSize
      hdfs_data_storage: DiskDataSize
      hdfs_name_tmp_storage: DiskTmpSize
      hdfs_data_tmp_storage: DiskTmpSize
    storage_class_resource:
      hdfs_name_data_storage: DiskNormalStorageClass
      hdfs_data_storage: DiskDataStorageClass
      hdfs_name_tmp_storage: DiskTmpStorageClass
      hdfs_data_tmp_storage: DiskTmpStorageClass

HYPERBASE:
  configuration:
    advanced_configs:
      default_group: hbase-site.xml
      groups:
      - name: hbase-site.xml
        env_cfg: HYPERBASE_HBASE_SITE_CONFIGS
        type: file


#IGNITOR:


INCEPTOR:
  configuration:
    advanced_configs:
      default_group: hive-site.xml
      groups:
      - name: hive-site.xml
        env_cfg: INCEPTOR_HIVE_SITE_CONFIGS
        type: file
      - name: extra_driver_opts
        env_cfg: EXTRA_DRIVER_OPTS
        type: config
      - name: extra_executor_opts
        env_cfg: EXTRA_EXECUTOR_OPTS
        type: config
  optional_dependencies:
  - hyperbase
  - search
  - txsql
  security:
    service_refer:
      metastore: inceptor


KAFKA:
  configuration:
    advanced_configs:
      default_group: server.properties
      groups:
      - name: server.properties
        env_cfg: KAFKA_SERVER_PROPERTIES
        type: file
    storage_resource:
      kafka_storage_config: DiskDataSize
      kafka_tmp_storage: DiskTmpSize
    storage_class_resource:
      kafka_storage_config: DiskDataStorageClass
      kafka_tmp_storage: DiskTmpStorageClass

KIBANA:
  optional_dependencies:
  - search

#KONG:

LOGSTASH:
  configuration:
    storage_resource:
      logstash_tmp_storage: DiskTmpSize
    storage_class_resource:
      logstash_tmp_storage: DiskTmpStorageClass
  optional_dependencies:
  - search

NOTEBOOK:
  configuration:
    advanced_configs:
      default_group: zeppelin-site.xml
      groups:
      - name: zeppelin-site.xml
        env_cfg: DISCOVER_ZEPPELIN_SITE_CONFIGS
        type: file

#NOTIFICATION:

#OCKLE:

PILOT:
  optional_dependencies:
  - inceptor

#REDIS:

RUBIK:
  configuration:
    advanced_configs:
      default_group: designer.properties
      groups:
      - name: designer.properties
        env_cfg: RUBIK_CONFIGS
        type: file

SEARCH:
  configuration:
    storage_resource:
      es_master_storage: DiskNormalSize
      es_data_storage: DiskDataSize
      es_client_storage: DiskNormalSize
    storage_class_resource:
      es_master_storage: DiskNormalStorageClass
      es_data_storage: DiskDataStorageClass
      es_client_storage: DiskNormalStorageClass

#SIMMAIL:

SLIPSTREAM:
  configuration:
    advanced_configs:
      default_group: hive-site.xml
      groups:
      - name: hive-site.xml
        env_cfg: INCEPTOR_HIVE_SITE_CONFIGS
        type: file
  optional_dependencies:
  - hyperbase
  security:
    service_refer:
      metastore: slipstream

SOPHON:
  configuration:
    advanced_configs:
      default_group: sophon_spark_master
      groups:
      - name: sophon_spark_master
        env_cfg: SOPHON_SPARK_MASTER
        type: config
      - name: livy.server.session.timeout-check
        env_cfg: LIVY_SERVER_SESSION_TIMEOUT_CHECK
        type: config
      - name: livy.server.session.timeout
        env_cfg: LIVY_SERVER_SESSION_TIMEOUT
        type: config
      - name: livy.server.yarn.app-lookup-timeout
        env_cfg: LIVY_SERVER_YARN_APP_LOOKUP_TIMEOUT
        type: config
      - name: sophon.k8s.session.cleanup.timeout.hours
        env_cfg: SOPHON_K8S_SESSION_CLEANUP_TIMEOUT_HOURS
        type: config
      - name: spring.http.multipart.max-file-size
        env_cfg: SPRING_HTTP_MULTIPART_MAX_FILE_SIZE
        type: config
      - name: spring.http.multipart.max-request-size
        env_cfg: SPRING_HTTP_MULTIPART_MAX_REQUEST_SIZE
        type: config
  optional_dependencies:
    - hyperbase
    - inceptor
    - search

SOPHONWEB:
  optional_dependencies:
    - hyperbase
    - inceptor
    - search

TCC:
  optional_dependencies:
  - gntenant

#TDCMILANO:

#TENON:

TERMINAL:
  configuration:
    storage_resource:
      terminal_data_storage: DiskDataSize
    storage_class_resource:
      terminal_data_storage: DiskDataStorageClass
  optional_dependencies:
  - hdfs
  - hyperbase
  - inceptor
  - search
  - yarn

TICKET:
  optional_dependencies:
  - gntenant
  - gn-tdc


TRANSPORTER:
  configuration:
    advanced_configs:
      default_group: tdt-site.xml
      groups:
      - name: tdt-site.xml
        env_cfg: TDT_TDT_SITE_CONFIGS
        type: file
    storage_resource:
      tdt_tmp_storage: DiskTmpSize
    storage_class_resource:
      tdt_tmp_storage: DiskTmpStorageClass

#TXSQL:

WORKFLOW:
  optional_dependencies:
  - transporter

YARN:
  configuration:
    advanced_configs:
      default_group: yarn-site.xml
      groups:
      - name: yarn-site.xml
        env_cfg: YARN_YARN_SITE_CONFIGS
        type: file
      - name: mapred_site
        env_cfg: YARN_MAPRED_SITE_CONFIGS
        type: file
    storage_resource:
      yarn_nodemanager_data_storage: DiskDataSize
      yarn_timelineserver_tmp_storage: DiskTmpSize
      yarn_nodemanager_tmp_storage: DiskTmpSize
      yarn_historyserver_tmp_storage: DiskTmpSize
      yarn_secondary_tmp_storage: DiskTmpSize
      yarn_resourcemanager_tmp_storage: DiskTmpSize
    storage_class_resource:
      yarn_nodemanager_data_storage: DiskDataStorageClass
      yarn_timelineserver_tmp_storage: DiskTmpStorageClass
      yarn_nodemanager_tmp_storage: DiskTmpStorageClass
      yarn_historyserver_tmp_storage: DiskTmpStorageClass
      yarn_secondary_tmp_storage: DiskTmpStorageClass
      yarn_resourcemanager_tmp_storage: DiskTmpStorageClass

ZOOKEEPER:
  configuration:
    storage_resource:
      zk_storage_config: DiskNormalSize
    storage_class_resource:
      zk_storage_config: DiskNormalStorageClass

#SMARTBI:

#NEXUS:
#  configuration:
#    priority_metrics:
#      nexus_priority: 0
#
#JENKINS:
#  configuration:
#    priority_metrics:
#      jenkins_priority: 0
#
#GITLAB:
#  configuration:
#    priority_metrics:
#      gitlab_priority: 10
#
#HARBOR:
#  configuration:
#    priority_metrics:
#      harbor_priority: 10
