# A unified configuration interface for TDC instances.
# Exampled data fields include:
# ----
#instance:
#  resource:
#    replicas:
#      - all instance needed replicas(ha+computing_unit+disks)
#    ha:
#      - example_replicas
#    computing_unit:
#      - example_replicas
#    disks:
#      sata_disks:
#        - example_disks
#  configuration:
#    environment:
#      - example_env_list
#  database:
#    - type: type
#      name: example_txsql_db_name
#  image:
#    default:
#      - example_image_config
#  security:
#   principal_list:
#     - example_principal_list
#   security_on:
#     - example_security_on_list
#   security_service:
#     env_cfg: ENV_CONFIG
#     type: SERVICE_TYPE
#   cas:
#      cas_on: cas_on
#      server_address: cas_server_url
#      login_address: cas_server_login_url

common:
  security:
    guardian_address: Transwarp_Guardian_Address
    guardian_ldap_server_address: Transwarp_Guardian_LDAP_Server_Address
    auto_injected_volumes: Transwarp_Auto_Injected_Volumes
    krb_realm: Transwarp_Realm
    krb_principal_suffix: Transwarp_Principal_Suffix

cas:
  resource:
    replicas:
      - cas_server_replicas
    ha:
      - cas_server_replicas
  configuration:
    environment:
      - cas_config_server_env_list
      - cas_server_env_list
      - cas_mgnt_server_env_list
  database:
    - name: cas_database_name

codis:
  resource:
    replicas:
      - codis_dash_replicas
      - codis_proxy_replicas
      - codis_fe_replicas
      - codis_server_replicas
    ha:
      - codis_dash_replicas
      - codis_proxy_replicas
      - codis_fe_replicas
    computing_unit:
      - codis_server_replicas
  configuration:
    environment:
      - codis_dash_env_list
      - codis_proxy_env_list
      - codis_server_env_list
      - codis_fe_env_list
  image:
    default:
      - codis_dash_image
      - codis_proxy_image
      - codis_server_image
      - codis_fe_image

discover:
  configuration:
    environment:
      - discover_env_list
  image:
    default:
      - discover_image
  security:
    principal_list:
      - discover
    security_on:
      - discover_mounted_kerberos
      - discover_authentication_enableguardian
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

elasticsearch:
  resource:
    replicas:
      - es_client_replicas
      - es_master_replicas
      - es_data_replicas
    ha:
      - es_client_replicas
      - es_master_replicas
    computing_unit:
      - es_data_replicas
  configuration:
    environment:
      - es_master_env_list
      - es_client_env_list
      - es_data_env_list
  image:
    default:
      - es_image
  security:
    principal_list:
      - es

filebeat:
  configuration:
    environment:
      - filebeat_env_list
  security:
    principal_list:
      - filebeat

filerobot:
  image:
    default:
        - filerobot_image
  security:
    principal_list:
      - filerobot
    security_on:
      - filerobot_mounted_kerberos

gn-tenant:
  resource:
    replicas:
      - gn_replicas
    ha:
      - gn_replicas

governor:
  configuration:
    environment:
      - governor_env_list
  database:
    - name: governor_txsql_db_name
  security:
    principal_list:
      - hbase
      - kafka
      - zookeeper
      - HTTP
    security_on:
      - governor_mounted_kerberos
#    security_service:
#      env_cfg: GUARDIAN_SERVICE_ID


governor-proxy:
  configuration:
    environment:
      - governor_proxy_env_list
  security:
    cas:
      server_address: cas_server_address

guardian:
  resource:
    replicas:
      - guardian_server_replicas
    ha:
      - guardian_server_replicas
  configuration:
    environment:
    - apacheds_env_list
    - guardian_server_env_list
  database:
    - name: guardian_database_name

guardian-cas:
  resource:
    replicas:
      - guardian_server_replicas
      - cas_server_replicas
    ha:
      - guardian_server_replicas
      - cas_server_replicas
  configuration:
    environment:
      - apacheds_env_list
      - guardian_server_env_list
      - cas_config_server_env_list
      - cas_server_env_list
      - cas_mgnt_server_env_list
  database:
    - type: guardian
      name: guardian_database_name
    - type: cas
      name: cas_database_name

hdfs:
  resource:
    replicas:
      - hdfs_httpfs_replicas
      - hdfs_data_replicas
      - hdfs_journal_replicas
      - hdfs_data_disk_replicas
    computing_unit:
      - hdfs_data_replicas
      - hdfs_journal_replicas
    disks:
      sata_disks:
        - hdfs_data_disk_replicas
  configuration:
    environment:
      - hdfs_name_env_list
      - hdfs_zkfc_env_list
      - hdfs_journal_env_list
      - hdfs_data_env_list
      - hdfs_httpfs_env_list
  image:
    default:
      - hdfs_data_image
      - hdfs_journal_image
      - hdfs_name_image
      - hdfs_zkfc_image
    hdfshttpfs:
      - hdfs_httpfs_image
  security:
    principal_list:
      - HTTP
      - hdfs
    security_on:
      - hdfs_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID
    cas:
      server_address: cas_server_address

hyperbase:
  resource:
    replicas:
      - hbase_master_replicas
      - hbase_thrift_replicas
      - hbase_rest_replicas
      - hbase_rs_replicas
    ha:
      - hbase_master_replicas
      - hbase_thrift_replicas
      - hbase_rest_replicas
    computing_unit:
      - hbase_rs_replicas
  configuration:
    environment:
      - hbase_master_env_list
      - hbase_rs_env_list
      - hbase_thrift_env_list
      - hbase_rest_env_list
  image:
    default:
      - hbase_master_image
      - hbase_rs_image
      - hbase_rest_image
      - hbase_thrift_image
  security:
    principal_list:
      - HTTP
      - hbase
    security_on:
      - hbase_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

inceptor:
  resource:
    replicas:
      - inceptor_replicas
      - inceptor_executor_replicas
      - inceptor_shuffle_dir_counts
    computing_unit:
      - inceptor_executor_replicas
    disks:
      sata_disks:
        - inceptor_shuffle_dir_counts
  configuration:
    environment:
      - inceptor_master_env_list
      - inceptor_executor_env_list
  image:
    default:
      - inceptor_executor_image
      - inceptor_master_image
  security:
    principal_list:
      - HTTP
      - hive
    security_on:
      - inceptor_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID
    cas:
      cas_on: cas_authentication_enabled
      server_address: cas_server_url_prefix
      login_address: cas_server_login_url

metastore:
  resource:
    replicas:
      - metastore_replicas
  configuration:
    environment:
      - metastore_env_list
      - mysql_env_list
  image:
    default:
      - metastore_image
      - mysql_image
  security:
    principal_list:
      - HTTP
      - hive
    security_on:
      - inceptor_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

kafka:
  resource:
    replicas:
      - kafka_replicas
    computing_unit:
      - kafka_replicas
  configuration:
    environment:
      - kafka_env_list
  image:
    default:
      - kafka_image
  security:
    principal_list:
      - kafka
    security_on:
      - kafka_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

kafka-manager:
  resource:
    replicas:
      - kafka_manager_replicas
    ha:
      - kafka_manager_replicas
  configuration:
    environment:
        - kafka_manager_env_list
  image:
    default:
      - kafka_manager_image
  security:
    principal_list:
      - kafka
    security_on:
      - kafka_manager_mounted_kerberos

kibana:
  resource:
    replicas:
      - kibana_replicas
    ha:
      - kibana_replicas
  configuration:
    environment:
      - kibana_env_list
  image:
    default:
      - kibana_image

kong:
  resource:
    replicas:
      - kong_replicas
    ha:
      - kong_replicas
  configuration:
    environment:
      - kong_env_list
  image:
    default:
      - kong_image

kong-dashboard:
  resource:
    replicas:
      - kong_dashboard_replicas
    ha:
      - kong_dashboard_replicas
  configuration:
    environment:
      - kong_dashboard_env_list
  image:
    default:
      - kong_dashboard_image

localcran:
  configuration:
    environment:
      - localcran_env_list
  image:
    default:
      - localcran_image

logstash:
  resource:
    replicas:
      - logstash_replicas
    computing_unit:
      - logstash_replicas
  configuration:
    environment:
      - logstash_env_list
  image:
    default:
      - logstash_image
  security:
    principal_list:
      - logstash

notebook:
  configuration:
    environment:
      - notebook_env_list
  image:
      default:
        - notebook_image
  security:
    principal_list:
      - discover
    security_on:
      - notebook_mounted_kerberos
      - notebook_authentication_enableguardian
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

notification:
  resource:
    replicas:
      - notification_replicas
    ha:
      - notification_replicas
  configuration:
    environment:
      - notification_env_list
  database:
    - name: notification_txsql_db_name
  image:
      default:
        - notification_image

pilot:
  resource:
    replicas:
      - pilot_replicas
    ha:
      - pilot_replicas
  configuration:
    environment:
      - pilot_env_list
  image:
    default:
      - pilot_image
  security:
    principal_list:
      - pilot
    security_on:
      - pilot_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID
    cas:
      server_url_prefix: cas_server_address
      server_context_path: CAS_SERVER_CONTEXT_PATH

rubik:
  resource:
    replicas:
      - rubik_replicas
    ha:
      - rubik_replicas
  configuration:
    environment:
      - rubik_env_list
  database:
    - name: MySQL_DATABASE
  image:
    default:
      - rubik_image
  security:
    principal_list:
      - rubik
    security_on:
      - RUBIK_AUTHENTICATION_ENABLEGUARDIAN
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID
    cas:
      server_url_prefix: cas_server_address
      server_context_path: CAS_SERVER_CONTEXT_PATH

slipstream:
  resource:
    replicas:
      - inceptor_replicas
      - inceptor_executor_replicas
      - inceptor_shuffle_dir_counts
    computing_unit:
      - inceptor_executor_replicas
    disks:
      sata_disks:
        - inceptor_shuffle_dir_counts
  configuration:
    environment:
      - inceptor_master_env_list
      - inceptor_executor_env_list
  image:
    default:
      - inceptor_executor_image
      - inceptor_master_image
  security:
    principal_list:
      - hive
      - HTTP
    security_on:
      - slipstream_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

sophon:
  security:
    principal_list:
      - hive
    security_on:
      - sophon_mounted_kerberos
#    security_service:
#      env_cfg: GUARDIAN_SERVICE_ID

sophonweb:
  security:
    principal_list:
      - hive
      - yarn
      - HTTP
    security_on:
      - sophon_mounted_kerberos
      - sophon_enable_kerberos

terminal:
  resource:
    replicas:
      - terminal_replicas
    ha:
      - terminal_replicas
  configuration:
    environment:
      - terminal_env_list
  image:
    default:
      - terminal_image

tcc:
  resource:
    replicas:
      - tcc_replicas
    ha:
      - tcc_replicas
  configuration:
    environment:
      - tcc_env_list
  database:
    - name: TCC_TXSQL_DB_NAME

tdt:
  resource:
    replicas:
      - tdt_replicas
    ha:
      - tdt_replicas
  configuration:
    environment:
      - tdt_env_list
  image:
    default:
      - tdt_image
  security:
    principal_list:
      - tdt
    security_on:
      - tdt_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID
    cas:
      server_address: cas_server_address
      server_context_path: CAS_SERVER_CONTEXT_PATH

ticket:
  database:
    - name: ticket_txsql_db_name
  resource:
    replicas:
      - ticket_replicas
    ha:
      - ticket_replicas
  configuration:
    environment:
      - ticket_env_list

txsql:
  resource:
    replicas:
      - txsql_replicas
  configuration:
    environment:
      - txsql_env_list
  image:
    default:
      - txsql_image

weblogic:
  resource:
    replicas:
      - ms_replicas
    computing_unit:
      - ms_replicas
  configuration:
    environment:
      - ms_env_list
  image:
    default:
      - weblogic_image

workflow:
  resource:
    replicas:
      - workflow_replicas
  configuration:
    environment:
      - workflow_env_list
  database:
    - name: workflow_txsql_db_name
  image:
    default:
      - workflow_image
  security:
    principal_list:
      - workflow
    security_on:
      - workflow_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID
    cas:
      server_address: cas_server_address
      server_context_path: CAS_SERVER_CONTEXT_PATH

yarn:
  resource:
    replicas:
      - yarn_node_replicas
      - yarn_data_disk_replicas
    computing_unit:
      - yarn_node_replicas
    disks:
      sata_disks:
        - yarn_data_disk_replicas
  configuration:
    environment:
      - resource_manager_env_list
      - history_server_env_list
      - node_manager_env_list
      - timeline_server_env_list
  image:
    default:
      - history_server_image
      - node_manager_image
      - resource_manager_image
      - timeline_server_image
  security:
    principal_list:
      - HTTP
      - mapred
      - yarn
    security_on:
      - yarn_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

zookeeper:
  resource:
    replicas:
      - zk_replicas
  configuration:
    environment:
      - zk_env_list
  image:
    default:
      - zk_image
  security:
    principal_list:
      - HTTP
      - zookeeper
    security_on:
      - zk_mounted_kerberos

smartbi:
  resource:
    replicas:
      - smartbi_tomcat_replicas
    ha:
      - smartbi_tomcat_replicas
  configuration:
    environment:
      - smartbi_tomcat_env_list
      - smartbi_mysql_env_list
  image:
    default:
      - smartbi_tomcat_image
      - smartbi_mysql_image

qa-jenkins:
  resource:
    replicas:
      - jenkins_replicas
    ha:
      - jenkins_replicas
  configuration:
    environment:
      - jenkins_env_list
  image:
    default:
      - jenkins_image

qa-nexus:
  resource:
    replicas:
      - nexus_replicas
    ha:
      - nexus_replicas
  configuration:
    environment:
      - nexus_env_list
  image:
    default:
      - nexus_image

gitlab:
  resource:
    replicas:
      - gitlab_replicas
    ha:
      - gitlab_replicas
  configuration:
    environment:
      - gitlab_env_list
      - redis_env_list
      - postgresql_env_list
  image:
    default:
      - gitlab_image
      - redis_image
      - postgresql_image

harbor:
  resource:
    replicas:
      - harbor_replicas
    ha:
      - harbor_replicas
  configuration:
    environment:
      - harbor_env_list
  image:
    default:
      - harbor_image

