common:
  LICENSE_ADDRESS: 172.16.1.41:2181
  Transwarp_DEBUG: false

DISCOVER:
  discover_image: 172.16.1.99/gold/discover-ide:transwarp-5.1
  localcran_image: 172.16.1.99/gold/discover-localcran:transwarp-5.1
  discover_ldap_password: Transwarp01!

GOVERNOR:
  governor_image: 172.16.1.99/gold/governor:transwarp-5.1
  notification_image: 172.16.1.99/gold/notification:transwarp-5.1

GUARDIAN:
  apacheds_image: 172.16.1.99/gold/apacheds:transwarp-5.1
  guardian_ds_root_password: Transwarp01!
  guardian_ds_admin_password: "123"
  guardian_ds_ha_enabled: false
  guardian_ds_partition_sync_on_write: "false"
  guardian_ds_conf_dir: /etc/guardian-apacheds/conf
  guardian_server_image: 172.16.1.99/gold/guardian:transwarp-5.1
  guardian_init_container_image: 172.16.1.41:5000/transwarp/guardian-init:latest
  guardian_server_tls_enabled: true
  guardian_server_key_store: /srv/guardian/server.keystore
  guardian_server_spnego_keytab: /srv/guardian/http.keytab
  guardian_server_key_store_pw: changeit
  fortress_bind_pwd: Transwarp01!
  cas_config_server_image: 172.16.1.99/zhaol/cas-config-server:latest
  cas_server_image: 172.16.1.99/zhaol/cas-server:latest
  cas_mgnt_server_image: 172.16.1.99/zhaol/cas-admin-server:latest
  gencerts_init_container_image: 172.16.1.99/zhaol/guardian-gencerts

HDFS:
  hdfs_data_image: 172.16.1.99/gold/hdfs:transwarp-5.1
  hdfs_journal_image: 172.16.1.99/gold/hdfs:transwarp-5.1
  hdfs_name_image: 172.16.1.99/gold/hdfs:transwarp-5.1
  hdfs_zkfc_image: 172.16.1.99/gold/hdfs:transwarp-5.1
  hdfs_httpfs_image: 172.16.1.99/gold/httpfs:transwarp-5.1
  zk_image: 172.16.1.99/gold/zookeeper:transwarp-5.1

HYPERBASE:
#  YARN_TIMELINE_ADDRESS: 0.0.0.0
  hbase_rest_image: 172.16.1.99/gold/hbase:transwarp-5.1
  hbase_thrift_image: 172.16.1.99/gold/hbase:transwarp-5.1
  hbase_master_image: 172.16.1.99/gold/hbase:transwarp-5.1
  hbase_rs_image: 172.16.1.99/gold/hbase:transwarp-5.1
  history_server_image: 172.16.1.99/gold/yarn:transwarp-5.1
  node_manager_image: 172.16.1.99/gold/yarn:transwarp-5.1
  resource_manager_image: 172.16.1.99/gold/yarn:transwarp-5.1
  timeline_server_image: 172.16.1.99/gold/yarn:transwarp-5.1
  Transwarp_Guardian_LDAP_Bind_Dn: uid=groupmapping/guardian,ou=System,ou=People,dc=tdh
  Transwarp_Guardian_LDAP_Bind_Password: Transwarp01!

INCEPTOR:
  inceptor_executor_image: 172.16.1.99/gold/inceptor:transwarp-5.1
  inceptor_master_image: 172.16.1.99/gold/inceptor:transwarp-5.1
  metastore_image: 172.16.1.99/gold/inceptor:transwarp-5.1
  mysql_image: 172.16.1.99/gold/inceptor:transwarp-5.1

KAFKA:
  kafka_image: 172.16.1.99/gold/kafka:transwarp-5.1
  zk_image: 172.16.1.99/gold/zookeeper:transwarp-5.1

KIBANA:
  kibana_image: 172.16.1.41:5000/tdc/kibana:4.2

NOTEBOOK:
  notebook_image: 172.16.1.99/gold/discover-notebook:transwarp-5.1
  localcran_image: 172.16.1.99/gold/discover-localcran:transwarp-5.1

PILOT:
  pilot_image: 172.16.1.99/gold/pilot:transwarp-5.1
  filerobot_image: 172.16.1.99/transwarp/filerobot:transwarp-5.1
  license_check: "False"

RUBIK:
  notification_image: 172.16.1.99/gold/notification:transwarp-5.1
  rubik_image: 172.16.1.99/transwarp/rubik:transwarp-5.1.0-rc3

SEARCH:
  es_image: 172.16.1.99/gold/search:transwarp-5.1
  es_head_image: 172.16.1.99/gold/search-head:transwarp-5.1

SLIPSTREAM:
  inceptor_executor_image: 172.16.1.99/gold/inceptor:transwarp-5.1
  inceptor_master_image: 172.16.1.99/gold/inceptor:transwarp-5.1
  metastore_image: 172.16.1.99/gold/inceptor:transwarp-5.1
  mysql_image: 172.16.1.99/gold/inceptor:transwarp-5.1

SOPHON:
  sophon_server_image: 172.16.1.99/postcommit/sophon-server:transwarp-5.1-2017-10-18-17-02-24-272

TCC:
  tcc_image: 172.16.1.41:5000/jenkins/tcc:devel
  tcc_memory_limit: 1.5
  tcc_cpu_limit: 1
  tcc_priority: 0
  tcc_replicas: 1
  guardian_server_tls_enabled: "true"
  guardian_username: "admin"
  guardian_password: "123"
  notification_kafka_url: 172.16.201.243:9092
  wormhole_server_url: http://wormhole.kube-system.svc:8090
  tcc_public_url: https://172.16.1.193/k8s-tcc
  cas_public_url: https://172.16.1.193/cas

TERMINAL:
  terminal_image: 172.16.1.45/transwarp/terminal:test

TICKET:
  ticket_image: 172.16.1.41:5000/jenkins/ticket:latest

TRANSPORTER:
  tdt_image: 172.16.1.99/transwarp/tdt:transwarp-5.1.0-rc3

TXSQL:
  txsql_image: 172.16.1.41:5000/mysql/mysql-server:5.5
  txsql_rootpassword: password

WORKFLOW:
  workflow_image: 172.16.1.99/gold/workflow_tos:transwarp-5.1

YARN:
#  YARN_TIMELINE_ADDRESS: 0.0.0.0
  history_server_image: 172.16.1.99/gold/yarn:transwarp-5.1
  node_manager_image: 172.16.1.99/gold/yarn:transwarp-5.1
  resource_manager_image: 172.16.1.99/gold/yarn:transwarp-5.1
  timeline_server_image: 172.16.1.99/gold/yarn:transwarp-5.1
