#----------------
# ockle Settings
#----------------

# Version range of Ockle to match current product-meta.
max-version: 0.3.4
min-version: 0.3.4

# A list of appliations that accept advanced configurations.
adv_config_white_list:
  - DISCOVER
  - KAFKA
  - HDFS
  - HYPERBASE
  - INCEPTOR
  - NOTEBOOK
  - RUBIK
  - SLIPSTREAM
  - TRANSPORTER
  - YARN

# A list of configs shared by multiple instances
instance_configs_sharing:
  - instance_type: rubik
    configs_sharing:
      - instance_type: inceptor
        dependency: txsql
        configs:
          - from:
              name: MySQL_DATABASE
            to:
              name: RUBIK_CONNECTION_DATABASE
              group: environment

# A list of TDC services that would be depended on by
# tenant context services.
# We take a prior assumption that only a single instance
# target application is deployed under `tdcsys` namespace.
platform_requirements:
  - application_type: OCKLE
    instance_type: ockle

  - application_type: GUARDIAN
    instance_type: guardian-cas

  - application_type: SIMMAIL
    instance_type: simmail

  - application_type: KONG
    instance_type: kong

  - application_type: SEARCH
    instance_type: elasticsearch

  - application_type: KAFKA
    instance_type: kafka

# A list of system services and ports
system_service:
  GUARDIAN:
    - port: 8380
      protocol: HTTPS
      alias: GuardianServer
    - port: 10389
      alias: LDAP
    - port: 1088
      alias: KDC
    - port: 8393
      protocol: HTTPS
      alias: CAS
  TICKET:
    - port: 11997
      protocol: HTTP

# A list of applications registered for TDC platform.
service_for_tdc:
  KONG:
    port: 8001
    dashboard_port: 8080
    protocol: HTTP

# A list of applications registered for tenant.
service_for_tenant:
  GUARDIAN:
    - port: 8380
      generate_name: gs
      protocol: HTTPS
      require_gateway_registration: true
      require_display: true
      alias: GuardianServer
    - port: 8393
      generate_name: cas-srv
      protocol: HTTPS
      require_gateway_registration: true
      require_display: false
      alias: CAS
    - port: 1088
      generate_name: "apacheds-master, apacheds-slave"
      require_gateway_registration: false
      require_display: true
      alias: KDC
  TCC:
    - port: 9042
      generate_name: tcc
      protocol: HTTP
      require_gateway_registration: true
      require_display: true
  KIBANA:
    - port: 5601
      generate_name: kibana
      protocol: HTTP
      require_gateway_registration: true
      require_display: false
  TICKET:
    - port: 11997
      generate_name: ticket
      protocol: HTTP
      require_gateway_registration: true
      require_display: false


# A list of services registered for development portal.
service_for_development:
  PILOT: 
  - port: 8086
    generate_name: pilot
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    display: 
      display_name: "报表工具"
      display_name_en: Pilot
      description: "基于Web的报表展现工具。轻量且灵活，支持多维度自助分析，提供二十余种报表样式。"
      description_en: "Pilot is a web-based data visualization service focusing on business intelligence reporting. It contains the drag and drop environment for data analysis, and there are more than 20 kinds of graphical charts embedded in the product."

  NOTEBOOK: 
  - port: 8686
    generate_name: notebook
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    display: 
      display_name: "数据分析交互平台"
      display_name_en: Notebook
      description: "轻量的科学计算开发工具。支持用R、Scala和SQL做分析，提供方便的交互界面实现机器学习。"
      description_en: "Web-based notebook that enables data-driven, interactive data analytics and collaborative documents with SQL, Scala, Python and more."

  WEBLOGIC:
  - port: 7001
    generate_name: weblogic-admin
    protocol: HTTP
    path: "/console"
    require_gateway_registration: true
    display:
      display_name: WebLogic
      display_name_en: WebLogic
      description: "开发、集成、部署和管理大型分布式Web应用、网络应用和数据库应用的Java应用服务器。"
      description_en: "Java EE application server."

  WORKFLOW:
  - port: 9091
    generate_name: workflow
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    display: 
      display_name: "工作流"
      display_name_en: Workflow
      description: "图形化的工作流服务平台。支持多种任务类型，提供丰富的工作流分析展现形式。"
      description_en: "The web-based tool to design, debug, schedule the job processes and tasks flow. It provides good analysis capabilities for all scheduled jobs so that tuning tasks are easy, besides good security controls are included."

  RUBIK: 
  - port: 32125
    generate_name: rubik
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    display: 
      display_name: "Cube设计工具"
      display_name_en: "Rubik "
      description: "OLAP Cube工具。用于OLAP模型设计与实例化，支持多种数据源，加速多维度分析。"
      description_en: "Rubik is a visualized tool to design OLAP Cubes for big data. With the acceleration of Cube, analytical query can speed up by 10x and give data analysts better interactive experience."

  GOVERNOR: 
  - port: 21000
    generate_name: governor
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    display: 
      display_name: "数据治理"
      display_name_en: Governor
      description: "元数据管理工具。可集中化管理元数据，监控更改历史，进行数据血缘分析和影响分析。"
      description_en: "Governor is a web-based metadata management and data governance tool. It gives user approaches to manage metadata including tables and SQL procedures, monitors all the data and program changing history, analyzes data lineage, and performs impact analysis."

  GOVERNORPROXY: 
  - port: 9527
    generate_name: governor-proxy
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    display: 
      display_name: "数据共享分析"
      display_name_en: "Governor Proxy"
      description: "数据共享分析工具，支持数据预览，申请，审批，下放，自助式查询，分析，报表展示，下载等功能。"
      description_en: "Data-sharing tool supports for various functions such as data preview, application, approval, sharing, self-service query, analysis, report display and download."

  TRANSPORTER: 
  - port: 8100
    generate_name: tdt
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    display: 
      display_name: "ETL工具"
      display_name_en: Transporter
      description: "可视化ETL管理工具。支持近实时数据同步，提供多种数据格式、转换操作及整合功能。"
      description_en: "Transporter is a web-based tool for designing and building ETL jobs for TDH. It offers near real-time data synchronization feature from RDBMS to TDH so that users can migrate the data analysis work from RDBMS to Hadoop for analytics and mining; various data sources including CSV, JDBC, XML, JSON, RDBMS are supported."

  GUARDIAN: 
  - port: 8380
    generate_name: gs
    protocol: HTTPS
    path: "/"
    require_gateway_registration: true
    alias: GuardianServer
    display: 
      display_name: "安全与权限"
      display_name_en: Guardian
      description: "统一的安全和资源管理服务平台。支持Kerberos和LDAP认证，提供细粒度的资源和权限管理。"
      description_en: "Guardian is a centralized security and resource management service in TDH. It supports both LDAP and Kerberos to make sure clusters are immune to attacks and security threats."

  KIBANA: 
  - port: 5601
    generate_name: kibana
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    display: 
      display_name: "日志分析"
      display_name_en: "Log Analysis Kibana"
      description: "日志诊断和检索平台。收集平台服务的日志，提供诊断和检索功能，方便系统运维和故障诊断。"
      description_en: "Kibana is a visualized log analysis platform. It presents the contents of the logs in your cluster, provides convenient log retrieval interface, and offers diverse graphs to shape your log data."

  INCEPTOR: 
  - port: 4040
    generate_name: inceptor2
    protocol: HTTP
    path: "/jobs"
    require_gateway_registration: true
    alias: INCEPTOR
    display: 
      display_name: "Inceptor任务监控"
      display_name_en: "Inceptor UI"
      description: "Inceptor任务监控页面。提供各应用运行状态、存储资源使用情况、环境和工作节点的信息。"
      description_en: "Inceptor UI is the web tool for Inceptor job & tasks monitoring. It provides fine granularity statistics for each SQL task, including latency, resource consumption, IO costs etc."
  - port: 10000
    generate_name: inceptor2
    require_gateway_registration: false
    alias: HiveServer2

  SLIPSTREAM: 
  - port: 4040
    generate_name: slipstream
    protocol: HTTP
    path: "/jobs"
    require_gateway_registration: true
    alias: SLIPSTREAM
    display: 
      display_name: "Slipstream任务监控"
      display_name_en: "Slipstream UI"
      description: "Slipstream任务监控页面，提供各流式应用和作业的运行状态以及资源使用情况。"
      description_en: "Slipstream UI is a web-based tool for monitoring streaming apps & jobs running on Slipstream as well as resource usage."
  - port: 10010
    generate_name: slipstream
    require_gateway_registration: false
    alias: HiveServer2

  SEARCH: 
  - port: 9100
    generate_name: "es-head"
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    require_service_type: NodePort
    display: 
      display_name: "ES管理器"
      display_name_en: "ES Head"
      description: "Elastic Search的网页版本的集群管理工具，支持数据的增删改查，并且可以通过语句进行可视化查询。"
      description_en: "ES Head is a web-based tool for Elastic Search cluster management, on-line query, data visualization, and CRUD operations. It is widely used by ES users for cluster operating and application development."

  SOPHON: 
  - port: 6066
    generate_name: sophonserver
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    require_service_type: NodePort
    display: 
      display_name: "人工智能Sophon"
      display_name_en: "Sophon AI"
      description: "整合了Tensorflow和MXNet的深度学习通用开发平台，帮助企业用户加速落地人工智能应用。"
      description_en: "Sophon is a common platform for deep learning development which is integrated with Tensorflow and MXNet. Sophon enables enterprise users to construct artificial intelligence application from scratch in a short period of time."

  TERMINAL: 
  - port: 5000
    generate_name: terminal
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    require_service_type: NodePort
    display: 
      display_name: "命令行终端"
      display_name_en: Terminal
      description: "网页版的操作命令行工具，集成了可以操作Transwarp所有服务的命令以及环境设置，方便的做各种运维操作以及大数据开发工作。"
      description_en: "A web based console with all utilities for Transwarp big data development and operation assembled, so it provides full capabilities as a console into a remote machine which has all developing environment set up."

  HYPERBASE: 
  - port: 60010
    generate_name: hbasemaster
    protocol: HTTP
    path: "/master-status"
    require_gateway_registration: true
    display: 
      display_name: "HyperBase管理"
      display_name_en: "HyperBase Master"
      description: "HyperBase管理页面方便运维人员有效的了解当前HyperBase集群的运行状况。"
      description_en: "The HyperBase Master UI is a useful tool to get an overview of the current status of the cluster. Users can get the basic configuration of Hyperbase, as well as load average of the cluster."

  HDFS: 
  - port: 50070
    generate_name: "hdfsnamenode, hdfssecondary"
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    require_service_type: ClusterIP
    display: 
      display_name: "HDFS管理"
      display_name_en: "HDFS Namenode UI"
      description: "HDFS管理服务用于HDFS的基本信息的查询，能够列出所有的HDFS datanode的基本信息，以及当前服务的一些运行统计数据。"
      description_en: "It lists the DataNodes in the cluster and basic statistics of the cluster. The web interface can also be used to browse the file system with permission."

  KAFKA: 
  - port: 8000
    generate_name: kafkamanager
    protocol: HTTP
    path: "/"
    require_gateway_registration: true
    display: 
      display_name: "Kafka管理"
      display_name_en: "Kafka Manager"
      description: "Kafka管理服务是用于进行Kafka管理的Web可视化操作平台。"
      description_en: "Kafka Manager is a tool for managing Kafka. It serves as a platform to inspect cluster state, where you can create topics with multiple configs, generate partition assignments, and perform dozens of helpful operations associated with Kafka."


  SOPHONWEB:
  - port: 30123
    generate_name: sophonweb
    protocol: "HTTP"
    path: "/"
    require_gateway_registration: true
    display:
      display_name: "人工智能Sophon"
      display_name_en: "Sophon AI"
      description: "Sophon提供一站式的界面操作，不论是普通的数据分析师和业务人员还是资深的数据科学家，都可以通过高效率的交互式体验和内置的行业模版快速构建AI模型。"
      description_en: "Sophon provides a powerful and friendly user interface. Both data/business analysts and senior data scientists can quickly build an AI model with built-in industry models and an efficient interactive experience."


  SMARTBI:
  - port: 18080
    generate_name: smartbi
    protocol: "HTTP"
    path: "/"
    require_gateway_registration: true
    display:
      display_name: "SmartBI"
      display_name_en: "SmartBI"
      description: "企业级商业智能应用平台。"
      description_en: "Modern business intelligence platform."

  JENKINS:
  - port: 8000
    generate_name: qa-jenkins
    hosts: true
    protocol: "HTTP"
    path: "/"
    require_gateway_registration: true
    display:
      display_name: "Jenkins"
      display_name_en: "Jenkins"
      description: "Jenkins是一款由Java编写的开源的持续集成工具"
      description_en: "Jenkins is an open source, continuous integration tool"

  NEXUS:
  - port: 8000
    generate_name: qa-nexus
    hosts: true
    protocol: "HTTP"
    path: "/"
    require_gateway_registration: true
    display:
      display_name: "Nexus"
      display_name_en: "Nexus"
      description: "Nexus是一个强大的仓库管理器"
      description_en: "Nexus is a powerful Maven repository manager"

  HARBOR:
  - port: 5000
    generate_name: harbor
    hosts: true
    protocol: "HTTP"
    path: "/"
    require_gateway_registration: true
    display:
      display_name: "Harbor"
      display_name_en: "Harbor"
      description: "Harbor是一个用于存储和分发Docker镜像的企业级Registry服务器"
      description_en: "Harbor is an enterprise-level Registry server for storing and distributing Docker images"

  GITLAB:
  - port: 8000
    generate_name: gitlab
    hosts: true
    protocol: "HTTP"
    path: "/"
    require_gateway_registration: true
    display:
      display_name: "Gitlab"
      display_name_en: "Gitlab"
      description: "Gitlab 是一款专业的代码托管仓库"
      description_en: "Gitlab is a professional code-managed repository"



# A list of instances that need to open ha for default
instance_open_ha:
  - tcc
#  - cas
#  - guardian
#  - guardian-cas
