image: 172.16.1.99/transwarp/base/builder:centos7
before_script:
    - source /etc/profile
    - source /root/.bashrc
stages:
  - precommit_build

precommit_build:
  stage: precommit_build
  script:
    - yum -y install jq
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@172.16.1.41:10080/pub/jsonnet.git jsonnet
    - cd jsonnet
    - make
    - export JSONNET_BIN=`pwd`/jsonnet
    - python setup.py install
    - cd -
    - sh -e ./testing.sh
  only:
    - /.*_develop_\d+/
    - /.*_master_\d+/
  tags:
    - k8s
