image: 172.16.1.99/transwarp/product_meta_builder:tdc-1.0
before_script:
    - source /etc/profile
    - source /root/.bashrc
    - export PUB_HARBOR=172.16.1.99
    - export PUB_MAJOR_VERSION=tdc-2.0

stages:
  - precommit_build
  - gold_build

precommit_build:
  stage: precommit_build
  script:
    - sh -e ./testing.sh
    - sh -e ./tests/precommit_validation.sh
  only:
    - /.*_master_\d+/
  tags:
    - k8s

gold_build:
  stage: gold_build
  script:
      - set -e
      - startdocker.sh &
      - sleep 90s
      - export PUB_PROJECT=gold
      - export PUB_TAG_MAJOR=$PUB_HARBOR/$PUB_PROJECT/product-meta:$PUB_MAJOR_VERSION
      - docker build --no-cache --force-rm -f Dockerfile -t $PUB_TAG_MAJOR .
      - docker push $PUB_TAG_MAJOR
      - ps aux | grep docker | grep -v "grep" |  awk '{print $2}' | xargs kill -9 || true
  only:
      - master@TDC/product-meta
  tags:
    - k8s
