image: 172.16.1.99/transwarp/base/builder:centos7
before_script:
    - source /etc/profile
    - source /root/.bashrc
    - export PUB_HARBOR=172.16.1.99
    - export PUB_MAJOR_VERSION=tdc-1.2

stages:
  - precommit_build
  - gold_build

precommit_build:
  stage: precommit_build
  script:
    - set -e
    - wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - rpm -ivh epel-release-latest-7.noarch.rpm
    - yum -y install jq
    - WORKDIR=`pwd`
    - cd /tmp
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@172.16.1.41:10080/TDC/utilities.git
    - cd utilities && chmod +x install_py.sh && ./install_py.sh 3.6.5
    - cd /tmp
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@172.16.1.41:10080/pub/jsonnet.git
    - cd jsonnet && make
    - export JSONNET_BIN=`pwd`/jsonnet
    - python3 setup.py install
    - cd $WORKDIR
    - sh -e ./testing.sh
  only:
    - /.*_master_\d+/
  tags:
    - k8s

gold_build:
  stage: gold_build
  script:
      - set -e
      - startdocker.sh &
      - sleep 90s
      - export PUB_PROJECT=gold
      - export PUB_TAG_MAJOR=$PUB_HARBOR/$PUB_PROJECT/product-meta:$PUB_MAJOR_VERSION
      - docker build --no-cache --force-rm -f Dockerfile -t $PUB_TAG_MAJOR .
      - docker push $PUB_TAG_MAJOR
      - ps aux | grep docker | grep -v "grep" |  awk '{print $2}' | xargs kill -9 || true
  only:
      - master@TDC/product-meta
  tags:
    - k8s
