image: 172.16.1.99/transwarp/base/builder:centos7
before_script:
    - source /etc/profile
    - source /root/.bashrc
    - export PUB_HARBOR=172.16.1.99
    - export PUB_MAJOR_VERSION=tdc-1.0

stages:
  - precommit_build
  - gold_build

precommit_build:
  stage: precommit_build
  script:
    - set -e
    - wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - rpm -ivh epel-release-latest-7.noarch.rpm
    - yum -y install jq
    - yum -y install python-devel
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@172.16.1.41:10080/pub/jsonnet.git jsonnet
    - cd jsonnet
    - make
    - export JSONNET_BIN=`pwd`/jsonnet
    - python setup.py install
    - cd -
    - sh -e ./testing.sh
  only:
    - /.*_develop_\d+/
    - /.*_master_\d+/
  tags:
    - k8s
    
gold_build:
  stage: gold_build
  script:
      - set -e
      - startdocker.sh &
      - sleep 90s
      - export PUB_PROJECT=gold
      - export PUB_TAG_MAJOR=$PUB_HARBOR/$PUB_PROJECT/product-meta:$PUB_MAJOR_VERSION
      - docker build --no-cache --force-rm -f Dockerfile -t $PUB_TAG_MAJOR .
      - docker login -u xiaming.chen -p Transwarp01 $PUB_HARBOR
      - docker push $PUB_TAG_MAJOR
      - ps aux | grep docker | grep -v "grep" |  awk '{print $2}' | xargs kill -9 || true
  only:
      - master
  tags:
    - k8s


