common:
  Transwarp_DEBUG: false

DISCOVER:
  discover_image: transwarp/discover-ide:transwarp-5.1.0-final
  localcran_image: transwarp/discover-localcran:transwarp-5.1.0-final
  discover_ldap_password: Transwarp01!

GOVERNOR:
  governor_image: transwarp/governor:transwarp-5.1.0-final
  notification_image: transwarp/notification:transwarp-5.1.0-final

GUARDIAN:
  apacheds_image: transwarp/apacheds:transwarp-5.1.0-final
  guardian_server_image: transwarp/guardian:transwarp-5.1.0-final
  guardian_init_container_image: transwarp/guardian-init:tdc-1.0
  gencerts_init_container_image: transwarp/guardian-gencerts:tdc-1.0
  cas_config_server_image: transwarp/cas-config-server:tdc-1.0
  cas_server_image: transwarp/cas-server:tdc-1.0
  cas_mgnt_server_image: transwarp/cas-admin-server:tdc-1.0
  guardian_ds_root_password: Transwarp01!
  guardian_ds_admin_password: "123"
  guardian_ds_ha_enabled: false
  guardian_ds_partition_sync_on_write: "false"
  guardian_ds_conf_dir: /etc/guardian-apacheds/conf
  guardian_server_tls_enabled: true
  guardian_server_key_store: /srv/guardian/server.keystore
  guardian_server_spnego_keytab: /srv/guardian/http.keytab
  guardian_server_key_store_pw: changeit
  fortress_bind_pwd: Transwarp01!
  guardian_ds_root_logger: "INFO,console"
  guardian_server_root_logger: "INFO,console"

HDFS:
  zk_image: transwarp/zookeeper:transwarp-5.1.0-final
  hdfs_data_image: transwarp/hdfs:transwarp-5.1.0-final
  hdfs_journal_image: transwarp/hdfs:transwarp-5.1.0-final
  hdfs_name_image: transwarp/hdfs:transwarp-5.1.0-final
  hdfs_zkfc_image: transwarp/hdfs:transwarp-5.1.0-final
  hdfs_httpfs_image: transwarp/httpfs:transwarp-5.1.0-final

HYPERBASE:
  # YARN_TIMELINE_ADDRESS: 0.0.0.0
  hbase_rest_image: transwarp/hbase:transwarp-5.1.0-final
  hbase_thrift_image: transwarp/hbase:transwarp-5.1.0-final
  hbase_master_image: transwarp/hbase:transwarp-5.1.0-final
  hbase_rs_image: transwarp/hbase:transwarp-5.1.0-final
  history_server_image: transwarp/yarn:transwarp-5.1.0-final
  node_manager_image: transwarp/yarn:transwarp-5.1.0-final
  resource_manager_image: transwarp/yarn:transwarp-5.1.0-final
  timeline_server_image: transwarp/yarn:transwarp-5.1.0-final
  Transwarp_Guardian_LDAP_Bind_Dn: uid=groupmapping/guardian,ou=System,ou=People,dc=tdh
  Transwarp_Guardian_LDAP_Bind_Password: Transwarp01!

INCEPTOR:
  inceptor_executor_image: transwarp/inceptor:transwarp-5.1.1-rc0
  inceptor_master_image: transwarp/inceptor:transwarp-5.1.1-rc0
  metastore_image: transwarp/inceptor:transwarp-5.1.1-rc0
  mysql_image: transwarp/inceptor:transwarp-5.1.1-rc0

KAFKA:
  kafka_image: transwarp/kafka:transwarp-5.1.0-final
  kafka_manager_image: transwarp/kafka-manager:tdc-1.0

KIBANA:
  kibana_image: transwarp/kibana:transwarp-5.1.0-final

NOTEBOOK:
  notebook_image: transwarp/discover-notebook:transwarp-5.1.0-final
  localcran_image: transwarp/discover-localcran:transwarp-5.1.0-final

PILOT:
  pilot_image: transwarp/pilot:transwarp-5.1.0-final
  filerobot_image: transwarp/filerobot:transwarp-5.1.0-final
  license_check: "False"

RUBIK:
  notification_image: transwarp/notification:transwarp-5.1.0-final
  rubik_image: transwarp/rubik:transwarp-5.1.0-final

SEARCH:
  es_image: transwarp/search:transwarp-5.1.0-final
  es_head_image: transwarp/search-head:transwarp-5.1.0-final

SLIPSTREAM:
  inceptor_executor_image: transwarp/inceptor:transwarp-5.1.1-rc0
  inceptor_master_image: transwarp/inceptor:transwarp-5.1.1-rc0
  metastore_image: transwarp/inceptor:transwarp-5.1.1-rc0
  mysql_image: transwarp/inceptor:transwarp-5.1.1-rc0
  inceptor_ui_port: 4044

SOPHON:
  sophon_server_image: transwarp/sophon-server:transwarp-5.1.0-final

TCC:
  tcc_image: transwarp/tcc:tdc-1.0
  GUARDIAN_USERNAME: "admin"
  GUARDIAN_PASSWORD: "123"

TERMINAL:
  terminal_image: transwarp/terminal:tdc-1.0

TICKET:
  ticket_image: transwarp/ticket:tdc-1.0
  notification_image: transwarp/notification:transwarp-5.1.0-final

TRANSPORTER:
  tdt_image: transwarp/tdt:transwarp-5.1.0-final

TXSQL:
  txsql_image: transwarp/mysql:transwarp-5.1.0-final
  txsql_rootpassword: password

WORKFLOW:
  workflow_image: transwarp/workflow:transwarp-5.1.1-final

YARN:
  # YARN_TIMELINE_ADDRESS: 0.0.0.0
  history_server_image: transwarp/yarn:transwarp-5.1.0-final
  node_manager_image: transwarp/yarn:transwarp-5.1.0-final
  resource_manager_image: transwarp/yarn:transwarp-5.1.0-final
  timeline_server_image: transwarp/yarn:transwarp-5.1.0-final
