#EXAMPLE:
#  configuration:
#    advanced_configs:
#      default: DEFAULT_CONFIGS
#      example_site.xml: EXAMPLE_SITE_CONFIGS
#  optional_dependencies:
#    - example_dependency
#  security:
#
common:
 configuration:
    advanced_configs:
#      capacity_scheduler:
#      server.properties:
#      zoo_cfg:
 security:
    guardian_address: Transwarp_Guardian_Address
    guardian_ldap_server_address: Transwarp_Guardian_LDAP_Server_Address
    auto_injected_volumes: Transwarp_Auto_Injected_Volumes

DISCOVER:
  configuration:
    advanced_configs:
      default: DISCOVER_SPARK_DEFAULTS_CONFIGS
      spark-defaults.conf: DISCOVER_SPARK_DEFAULTS_CONFIGS

#GOVERNOR:

HDFS:
  configuration:
    advanced_configs:
      default: HDFS_HDFS_SITE_CONFIGS
      hdfs-site.xml: HDFS_HDFS_SITE_CONFIGS
      core-site.xml: HDFS_CORE_SITE_CONFIGS

HYPERBASE:
  configuration:
    advanced_configs:
      default: HYPERBASE_HBASE_SITE_CONFIGS
      hbase-site.xml: HYPERBASE_HBASE_SITE_CONFIGS

INCEPTOR:
  configuration:
    advanced_configs:
      default: INCEPTOR_HIVE_SITE_CONFIGS
      hive-site.xml: INCEPTOR_HIVE_SITE_CONFIGS
  optional_dependencies:
    - hyperbase
    - search

#KAFKA:

KIBANA:
  optional_dependencies:
    - search

#KONG:

LOGSTASH:
  optional_dependencies:
    - search

NOTEBOOK:
  configuration:
    advanced_configs:
      default: DISCOVER_ZEPPELIN_SITE_CONFIGS
      zeppelin-site.xml: DISCOVER_ZEPPELIN_SITE_CONFIGS

#NOTIFICATION:

#PILOT:

#RUBIK:

SEARCH:
  configuration:
    advanced_configs:
      default: ELASTICSEARCH_ELASTICSEARCH_YML_CONFIGS
      elasticsearch.yml: ELASTICSEARCH_ELASTICSEARCH_YML_CONFIGS


SLIPSTREAM:
  configuration:
    advanced_configs:
      default: INCEPTOR_HIVE_SITE_CONFIGS
      hive-site.xml: INCEPTOR_HIVE_SITE_CONFIGS

TERMINAL:
  optional_dependencies:
    - hdfs
    - hyperbase
    - inceptor
    - search
    - yarn

#TRANSPORTER:

#TXSQL:

WORKFLOW:
  optional_dependencies:
    - transporter

YARN:
  configuration:
    advanced_configs:
      default: YARN_YARN_SITE_CONFIGS
      mapred_site: YARN_MAPRED_SITE_CONFIGS
      yarn-site.xml: YARN_YARN_SITE_CONFIGS
