#APPLICATION:
#  configuration:
#    default_file: example_site.xml
#    environment:
#      example_site.xml: EXAMPLE_SITE_CONFIGS
#    storage_resource:  # Mapping for jsonnet storage size, see WARP-17653
#      normal_size_metric_from_template: DiskNormalSize
#      data_size_metric_from_template: DiskDataSize
#      log_size_metric_from_template: DiskLogSize
#      tmp_size_metric_from_template: DiskTmpSize
#  optional_dependencies:
#    - example_dependency
#  security:
#    service_refer:
#      instance_type_1: instance_type_2

DISCOVER:
  configuration:
    default_file: spark-defaults.conf
    environment:
      spark-defaults.conf: DISCOVER_SPARK_DEFAULTS_CONFIGS

#GOVERNOR:

GUARDIAN:
  configuration:
    storage_resource:
      guardian_server_volume_storage: DiskNormalSize

HDFS:
  configuration:
    default_file: hdfs-site.xml
    environment:
      hdfs-site.xml: HDFS_HDFS_SITE_CONFIGS
      core-site.xml: HDFS_CORE_SITE_CONFIGS
    storage_resource:
      hdfs_name_data_storage: DiskNormalSize
      hdfs_data_storage: DiskDataSize
      hdfs_name_tmp_storage: DiskTmpSize
      hdfs_data_tmp_storage: DiskTmpSize

HYPERBASE:
  configuration:
    default_file: hbase-site.xml
    environment:
      hbase-site.xml: HYPERBASE_HBASE_SITE_CONFIGS

INCEPTOR:
  configuration:
    default_file: hive-site.xml
    environment:
      hive-site.xml: INCEPTOR_HIVE_SITE_CONFIGS
  optional_dependencies:
    - hyperbase
    - search
  security:
    service_refer:
      metastore: inceptor

KAFKA:
  configuration:
    default_file: server.properties
    environment:
      server.properties: KAFKA_SERVER_PROPERTIES
    storage_resource:
      kafka_storage_config: DiskDataSize
      kafka_tmp_storage: DiskTmpSize

KIBANA:
  optional_dependencies:
    - search

#KONG:

LOGSTASH:
  configuration:
    storage_resource:
      logstash_tmp_storage: DiskTmpSize
  optional_dependencies:
    - search

NOTEBOOK:
  configuration:
    default_file: zeppelin-site.xml
    environment:
      zeppelin-site.xml: DISCOVER_ZEPPELIN_SITE_CONFIGS

#NOTIFICATION:

#PILOT:

#RUBIK:

SEARCH:
 configuration:
   # default_file: elasticsearch.yml
   # environment:
   #   elasticsearch.yml: ELASTICSEARCH_YML_CONFIGS
   storage_resource:
     es_master_storage: DiskNormalSize
     es_data_storage: DiskDataSize
     es_client_storage: DiskNormalSize

SLIPSTREAM:
  configuration:
    default_file: hive-site.xml
    environment:
      hive-site.xml: INCEPTOR_HIVE_SITE_CONFIGS
  security:
    service_refer:
      metastore: slipstream

TERMINAL:
  optional_dependencies:
    - hdfs
    - hyperbase
    - inceptor
    - search
    - yarn

TRANSPORTER:
  configuration:
    default_file: tdt-site.xml
    environment:
      tdt-site.xml: TDT_TDT_SITE_CONFIGS
    storage_resource:
      tdt_tmp_storage: DiskTmpSize

#TXSQL:

WORKFLOW:
  optional_dependencies:
    - transporter

YARN:
  configuration:
    default_file: yarn-site.xml
    environment:
      mapred_site: YARN_MAPRED_SITE_CONFIGS
      yarn-site.xml: YARN_YARN_SITE_CONFIGS
    storage_resource:
      yarn_nodemanager_data_storage: DiskDataSize
      yarn_timelineserver_tmp_storage: DiskTmpSize
      yarn_nodemanager_tmp_storage: DiskTmpSize
      yarn_historyserver_tmp_storage: DiskTmpSize
      yarn_secondary_tmp_storage: DiskTmpSize
      yarn_resourcemanager_tmp_storage: DiskTmpSize

ZOOKEEPER:
  configuration:
    storage_resource:
      zk_storage_config: DiskNormalSize
