#APPLICATION:
#  configuration:
#    default_file: example_site.xml
#    environment:
#      example_site.xml: EXAMPLE_SITE_CONFIGS
#  optional_dependencies:
#    - example_dependency
#
DISCOVER:
  configuration:
    default_file: spark-defaults.conf
    environment:
      spark-defaults.conf: DISCOVER_SPARK_DEFAULTS_CONFIGS

#GOVERNOR:

HDFS:
  configuration:
    default_file: hdfs-site.xml
    environment:
      hdfs-site.xml: HDFS_HDFS_SITE_CONFIGS
      core-site.xml: HDFS_CORE_SITE_CONFIGS

HYPERBASE:
  configuration:
    default_file: hbase-site.xml
    environment:
      hbase-site.xml: HYPERBASE_HBASE_SITE_CONFIGS

INCEPTOR:
  configuration:
    default_file: hive-site.xml
    environment:
      hive-site.xml: INCEPTOR_HIVE_SITE_CONFIGS
  optional_dependencies:
    - hyperbase
    - search

KAFKA:
  configuration:
    default_file: server.properties
    environment:
      server.properties: KAFKA_SERVER_PROPERTIES

KIBANA:
  optional_dependencies:
    - search

#KONG:

LOGSTASH:
  optional_dependencies:
    - search

NOTEBOOK:
  configuration:
    default_file: zeppelin-site.xml
    environment:
      zeppelin-site.xml: DISCOVER_ZEPPELIN_SITE_CONFIGS

#NOTIFICATION:

#PILOT:

#RUBIK:

#SEARCH:
#  configuration:
#    default_file: elasticsearch.yml
#    environment:
#      elasticsearch.yml: ELASTICSEARCH_YML_CONFIGS


SLIPSTREAM:
  configuration:
    default_file: hive-site.xml
    environment:
      hive-site.xml: INCEPTOR_HIVE_SITE_CONFIGS

TERMINAL:
  optional_dependencies:
    - hdfs
    - hyperbase
    - inceptor
    - search
    - yarn

#TRANSPORTER:

#TXSQL:

WORKFLOW:
  optional_dependencies:
    - transporter

YARN:
  configuration:
    default_file: yarn-site.xml
    environment:
      mapred_site: YARN_MAPRED_SITE_CONFIGS
      yarn-site.xml: YARN_YARN_SITE_CONFIGS
