#EXAMPLE:
#  configuration:
#    advanced_configs:
#      default: DEFAULT_CONFIGS
#      example_site.xml: EXAMPLE_SITE_CONFIGS
#  optional_dependencies:
#    - example_dependency
#  security:
#
common:
 configuration:
    advanced_configs:
      capacity_scheduler:
      mapred_site:
      yarn-site.xml: YARN_YARN_SITE_CONFIGS
      zeppelin-site.xml:
      server.properties:
      zoo_cfg:
      hive-site.xml: INCEPTOR_HIVE_SITE_CONFIGS
      hdfs-site.xml: HDFS_HDFS_SITE_CONFIGS
      core-site.xml:
      hbase-site.xml:
 security:
    guardian_address: Transwarp_Guardian_Address
    guardian_ldap_server_address: Transwarp_Guardian_LDAP_Server_Address
    auto_injected_volumes: Transwarp_Auto_Injected_Volumes

#DISCOVER:

#GOVERNOR:

HDFS:
  configuration:
    advanced_configs:
      default: HDFS_HDFS_SITE_CONFIGS

#HYPERBASE:

INCEPTOR:
  configuration:
    advanced_configs:
      default: INCEPTOR_HIVE_SITE_CONFIGS
  optional_dependencies:
    - hyperbase
    - search

#KAFKA:

KIBANA:
  optional_dependencies:
    - search

#KONG:

LOGSTASH:
  optional_dependencies:
    - search

#NOTEBOOK:

#NOTIFICATION:

#PILOT:

#RUBIK:

#SEARCH:

SLIPSTREAM:
  configuration:
    advanced_configs:
      default: INCEPTOR_HIVE_SITE_CONFIGS

TERMINAL:
  optional_dependencies:
    - hdfs
    - hyperbase
    - inceptor
    - search
    - yarn

#TRANSPORTER:

#TXSQL:

WORKFLOW:
  optional_dependencies:
    - transporter

YARN:
  configuration:
    advanced_configs:
      default: YARN_YARN_SITE_CONFIGS
