#APPLICATION:
#  configuration:
#   advanced_configs:
#      default_group: group_name
#      groups:
#        - name: group_name
#          env_cfg: ENV_CONFIG
#          type: group_type (file/config)
#    storage_resource:  # Mapping for jsonnet storage size, see WARP-17653
#      normal_size_metric_from_template: DiskNormalSize
#      data_size_metric_from_template: DiskDataSize
#      log_size_metric_from_template: DiskLogSize
#      tmp_size_metric_from_template: DiskTmpSize
#  optional_dependencies:
#    - example_dependency
#  security:
#    service_refer:
#      instance_type_1: instance_type_2

DISCOVER:
  configuration:
    advanced_configs:
      default_group: spark-defaults.conf
      groups:
        - name: spark-defaults.conf
          env_cfg: DISCOVER_SPARK_DEFAULTS_CONFIGS
          type: file

#GOVERNOR:

GUARDIAN:
  configuration:
    storage_resource:
      guardian_server_volume_storage: DiskNormalSize

HDFS:
  configuration:
    advanced_configs:
      default_group: hdfs-site.xml
      groups:
        - name: hdfs-site.xml
          env_cfg: HDFS_HDFS_SITE_CONFIGS
          type: file
        - name: core-site.xml
          env_cfg: HDFS_CORE_SITE_CONFIGS
          type: file
    storage_resource:
      hdfs_name_data_storage: DiskNormalSize
      hdfs_data_storage: DiskDataSize
      hdfs_name_tmp_storage: DiskTmpSize
      hdfs_data_tmp_storage: DiskTmpSize

HYPERBASE:
  configuration:
    advanced_configs:
      default_group: hbase-site.xml
      groups:
        - name: hbase-site.xml
          env_cfg: HYPERBASE_HBASE_SITE_CONFIGS
          type: file

INCEPTOR:
  configuration:
    advanced_configs:
      default_group: hive-site.xml
      groups:
        - name: hive-site.xml
          env_cfg: INCEPTOR_HIVE_SITE_CONFIGS
          type: file
        - name: extra_driver_opts
          env_cfg: EXTRA_DRIVER_OPTS
          type: config
        - name: extra_executor_opts
          env_cfg: EXTRA_EXECUTOR_OPTS
          type: config
  optional_dependencies:
    - hyperbase
    - search
  security:
    service_refer:
      metastore: inceptor

KAFKA:
  configuration:
    advanced_configs:
      default_group: server.properties
      groups:
        - name: server.properties
          env_cfg: KAFKA_SERVER_PROPERTIES
          type: file
    storage_resource:
      kafka_storage_config: DiskDataSize
      kafka_tmp_storage: DiskTmpSize

KIBANA:
  optional_dependencies:
    - search

#KONG:

LOGSTASH:
  configuration:
    storage_resource:
      logstash_tmp_storage: DiskTmpSize
  optional_dependencies:
    - search

NOTEBOOK:
  configuration:
    advanced_configs:
      default_group: zeppelin-site.xml
      groups:
        - name: zeppelin-site.xml
          env_cfg: DISCOVER_ZEPPELIN_SITE_CONFIGS
          type: file

#NOTIFICATION:

#PILOT:

#RUBIK:

SEARCH:
 configuration:
   storage_resource:
     es_master_storage: DiskNormalSize
     es_data_storage: DiskDataSize
     es_client_storage: DiskNormalSize

SLIPSTREAM:
  configuration:
    advanced_configs:
      default_group: hive-site.xml
      groups:
        - name: hive-site.xml
          env_cfg: INCEPTOR_HIVE_SITE_CONFIGS
          type: file
  security:
    service_refer:
      metastore: slipstream

TERMINAL:
  optional_dependencies:
    - hdfs
    - hyperbase
    - inceptor
    - search
    - yarn

TRANSPORTER:
  configuration:
   advanced_configs:
    default_group: tdt-site.xml
    groups:
      - name: tdt-site.xml
        env_cfg: TDT_TDT_SITE_CONFIGS
        type: file
    storage_resource:
      tdt_tmp_storage: DiskTmpSize

#TXSQL:

WORKFLOW:
  optional_dependencies:
    - transporter

YARN:
  configuration:
    advanced_configs:
      default_group: yarn-site.xml
      groups:
        - name: yarn-site.xml
          env_cfg: YARN_YARN_SITE_CONFIGS
          type: file
        - name: mapred_site
          env_cfg: YARN_MAPRED_SITE_CONFIGS
          type: file
    storage_resource:
      yarn_nodemanager_data_storage: DiskDataSize
      yarn_timelineserver_tmp_storage: DiskTmpSize
      yarn_nodemanager_tmp_storage: DiskTmpSize
      yarn_historyserver_tmp_storage: DiskTmpSize
      yarn_secondary_tmp_storage: DiskTmpSize
      yarn_resourcemanager_tmp_storage: DiskTmpSize

ZOOKEEPER:
  configuration:
    storage_resource:
      zk_storage_config: DiskNormalSize
