- instance_type: rubik
  configs_sharing:
    - instance_type: inceptor
      dependency: txsql
      configs:
        - from:
            name: MySQL_DATABASE
          to:
            name: RUBIK_CONNECTION_DATABASE
            group: environment
