# A unified configuration interface for TDC instances.
# Exampled data fields include:
# ----
#instance:
#  resource:
#    node_num:
#     default:
#       - example_replicas
#     singleton:
#       - example_replicas
#    disks:
#      sata_disks:
#        - example_disks
#  configuration:
#    environment:
#      - example_env_list
#  database:
#    name: example_txsql_db_name
#  image:
#    default:
#      - example_image_config
#  security:
#   principal_list:
#     - example_principal_list
#   security_on:
#     - example_security_on_list
#   security_service:
#     env_cfg: ENV_CONFIG
#     type: SERVICE_TYPE

common:
  security:
    guardian_address: Transwarp_Guardian_Address
    guardian_ldap_server_address: Transwarp_Guardian_LDAP_Server_Address
    auto_injected_volumes: Transwarp_Auto_Injected_Volumes

cas:
  configuration:
    environment:
      - cas_config_server_env_list
      - cas_server_env_list
      - cas_mgnt_server_env_list
  database:
    name: cas_database_name

codis:
  resource:
    node_num:
      default:
        - codis_server_replicas
      singleton:
        - codis_dash_replicas
        - codis_proxy_replicas
        - codis_fe_replicas
  configuration:
    environment:
      - codis_dash_env_list
      - codis_proxy_env_list
      - codis_server_env_list
      - codis_fe_env_list
  image:
    default:
      - codis_dash_image
      - codis_proxy_image
      - codis_server_image
      - codis_fe_image

discover:
  configuration:
    environment:
      - discover_env_list
  image:
    default:
      - discover_image
  security:
    principal_list:
      - discover
    security_on:
      - discover_mounted_kerberos
      - discover_authentication_enableguardian
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

elasticsearch:
  resource:
    node_num:
      default:
        - es_data_replicas
      singleton:
        - es_client_replicas
        - es_master_replicas
  configuration:
    environment:
      - es_master_env_list
      - es_client_env_list
      - es_data_env_list
  image:
    default:
      - es_image
  security:
    principal_list:
      - es

filebeat:
  configuration:
    environment:
      - filebeat_env_list
  security:
    principal_list:
      - filebeat

filerobot:
  image:
    default:
        - filerobot_image
  security:
    principal_list:
      - filerobot
    security_on:
      - filerobot_mounted_kerberos

governor:
  configuration:
    environment:
      - governor_env_list
  database:
    name: governor_txsql_db_name
  security:
    principal_list:
      - hbase
      - kafka
      - zookeeper
    security_on:
      - governor_mounted_kerberos
#    security_service:
#      env_cfg: GUARDIAN_SERVICE_ID

guardian:
  configuration:
    environment:
    - apacheds_env_list
    - guardian_server_env_list

hdfs:
  resource:
    node_num:
      default:
        - hdfs_data_replicas
        - hdfs_journal_replicas
      singleton:
        - hdfs_httpfs_replicas
    disks:
      sata_disks:
        - hdfs_data_disk_replicas
  configuration:
    environment:
      - hdfs_name_env_list
      - hdfs_zkfc_env_list
      - hdfs_journal_env_list
      - hdfs_data_env_list
      - hdfs_httpfs_env_list
  image:
    default:
      - hdfs_data_image
      - hdfs_journal_image
      - hdfs_name_image
      - hdfs_zkfc_image
    hdfshttpfs:
      - hdfs_httpfs_image
  security:
    principal_list:
      - HTTP
      - hdfs
    security_on:
      - hdfs_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

hyperbase:
  resource:
    node_num:
      default:
        - hbase_rs_replicas
      singleton:
        - hbase_master_replicas
        - hbase_thrift_replicas
        - hbase_rest_replicas
  configuration:
    environment:
      - hbase_master_env_list
      - hbase_rs_env_list
      - hbase_thrift_env_list
      - hbase_rest_env_list
  image:
    default:
      - hbase_master_image
      - hbase_rs_image
      - hbase_rest_image
      - hbase_thrift_image
  security:
    principal_list:
      - HTTP
      - hbase
    security_on:
      - hbase_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

inceptor:
  resource:
    node_num:
      default:
        - inceptor_executor_replicas
      singleton:
        - inceptor_replicas
    disks:
      sata_disks:
        - inceptor_shuffle_dir_counts
  configuration:
    environment:
      - inceptor_master_env_list
      - inceptor_executor_env_list
  image:
    default:
      - inceptor_executor_image
      - inceptor_master_image
  security:
    principal_list:
      - HTTP
      - hive
    security_on:
      - inceptor_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

metastore:
  resource:
    node_num:
      singleton:
        - metastore_replicas
  configuration:
    environment:
      - metastore_env_list
      - mysql_env_list
  image:
    default:
      - metastore_image
      - mysql_image
  security:
    principal_list:
      - HTTP
      - hive
    security_on:
      - inceptor_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

kafka:
  resource:
    node_num:
      default:
        - kafka_replicas
  configuration:
    environment:
      - kafka_env_list
  image:
    default:
      - kafka_image
  security:
    principal_list:
      - kafka
    security_on:
      - kafka_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

kafka-manager:
  resource:
    node_num:
      singleton:
        - kafka_manager_replicas
  configuration:
    environment:
        - kafka_manager_env_list
  image:
    default:
      - kafka_manager_image

kibana:
  resource:
    node_num:
      singleton:
        - kibana_replicas
  configuration:
    environment:
      - kibana_env_list
  image:
    default:
      - kibana_image

kong:
  resource:
    node_num:
      singleton:
        - kong_replicas
  configuration:
    environment:
      - kong_env_list
  image:
    default:
      - kong_image

kong-dashboard:
  resource:
    node_num:
      singleton:
        - kong_dashboard_replicas
  configuration:
    environment:
      - kong_dashboard_env_list
  image:
    default:
      - kong_dashboard_image

localcran:
  configuration:
    environment:
      - localcran_env_list
  image:
    default:
      - localcran_image

logstash:
  resource:
    node_num:
      default:
        - logstash_replicas
  configuration:
    environment:
      - logstash_env_list
  image:
    default:
      - logstash_image
  security:
    principal_list:
      - logstash

notebook:
  configuration:
    environment:
      - notebook_env_list
  image:
      default:
        - notebook_image
  security:
    principal_list:
      - discover
    security_on:
      - notebook_mounted_kerberos
      - notebook_authentication_enableguardian
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

notification:
  configuration:
    environment:
      - notification_env_list
  database:
    name: notification_txsql_db_name
  image:
      default:
        - notification_image
  resource:
    node_num:
      singleton:
        - notification_replicas

pilot:
  configuration:
    environment:
      - pilot_env_list
  image:
    default:
      - pilot_image
  security:
    principal_list:
      - pilot
    security_on:
      - pilot_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

rubik:
  resource:
    node_num:
      singleton:
        - rubik_replicas
  configuration:
    environment:
      - rubik_env_list
  database:
    name: MySQL_DATABASE
  image:
    default:
      - rubik_image
  security:
    principal_list:
      - rubik
    security_on:
      - RUBIK_AUTHENTICATION_ENABLEGUARDIAN
#    security_service:
#      env_cfg: GUARDIAN_SERVICE_ID

slipstream:
  resource:
    node_num:
      default:
        - inceptor_executor_replicas
      singleton:
        - inceptor_replicas
    disks:
      sata_disks:
        - inceptor_shuffle_dir_counts
  configuration:
    environment:
      - inceptor_master_env_list
      - inceptor_executor_env_list
  image:
    default:
      - inceptor_executor_image
      - inceptor_master_image
  security:
    principal_list:
      - hive
      - HTTP
    security_on:
      - slipstream_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

sophon:
  security:
    principal_list:
      - hive
    security_on:
      - sophon_mounted_kerberos
#    security_service:
#      env_cfg: GUARDIAN_SERVICE_ID

terminal:
  resource:
    node_num:
      singleton:
        - terminal_replicas
  configuration:
    environment:
      - terminal_env_list
  image:
    default:
      - terminal_image

tcc:
  resource:
    node_num:
      singleton:
        - tcc_replicas
  configuration:
    environment:
      - tcc_env_list
  database:
    name: TCC_TXSQL_DB_NAME

tdt:
  resource:
    node_num:
      singleton:
        - tdt_replicas
  configuration:
    environment:
      - tdt_env_list
  image:
    default:
      - tdt_image
  security:
    principal_list:
      - tdt
    security_on:
      - tdt_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

ticket:
  database:
    name: ticket_txsql_db_name
  resource:
    node_num:
      singleton:
        - ticket_replicas

txsql:
  resource:
    node_num:
      singleton:
        - txsql_replicas
  configuration:
    environment:
      - txsql_env_list
  image:
    default:
      - txsql_image

workflow:
  resource:
    node_num:
      singleton:
        - workflow_replicas
  configuration:
    environment:
      - workflow_env_list
  database:
    name: workflow_txsql_db_name
  image:
    default:
      - workflow_image
  security:
    principal_list:
      - workflow
    security_on:
      - workflow_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

yarn:
  resource:
    node_num:
      default:
        - yarn_node_replicas
    disks:
      sata_disks:
        - yarn_data_disk_replicas
  configuration:
    environment:
      - resource_manager_env_list
      - history_server_env_list
      - node_manager_env_list
      - timeline_server_env_list
  image:
    default:
      - history_server_image
      - node_manager_image
      - resource_manager_image
      - timeline_server_image
  security:
    principal_list:
      - HTTP
      - mapred
      - yarn
    security_on:
      - yarn_mounted_kerberos
    security_service:
      env_cfg: GUARDIAN_SERVICE_ID

zookeeper:
  configuration:
    environment:
      - zk_env_list
  image:
    default:
      - zk_image
  security:
    principal_list:
      - HTTP
      - zookeeper
    security_on:
      - zk_mounted_kerberos
